// Mocks generated by Mockito 5.3.2 from annotations
// in todo/todo_over_view/repository/todo_repository.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:todo/filter/model/filter.dart' as _i5;
import 'package:todo/todo_over_view/model/todo.dart' as _i4;
import 'package:todo/todo_over_view/repository/todo_repository.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TodoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoRepository extends _i1.Mock implements _i2.TodoRepository {
  @override
  void delete(int? id) => super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i3.Future<List<_i4.Todo>> fetch({required _i5.Filter? filter}) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetch,
          [],
          {#filter: filter},
        ),
        returnValue: _i3.Future<List<_i4.Todo>>.value(<_i4.Todo>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.Todo>>.value(<_i4.Todo>[]),
      ) as _i3.Future<List<_i4.Todo>>);
  @override
  void insert(_i4.Todo? todo) => super.noSuchMethod(
        Invocation.method(
          #insert,
          [todo],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void update(_i4.Todo? todo) => super.noSuchMethod(
        Invocation.method(
          #update,
          [todo],
        ),
        returnValueForMissingStub: null,
      );
}
